### ISSUE TITLE
App crashing after web input.

### ISSUE THREAD

**Issue by larobert** [mattvv/lineplease#52]
I have input my script and trying to have it read back to me in it's entirety, but only gets through the a few lines then crashes.

**Comment by mattvv** [comment]
Hi larobert - Please see #50 for this issue. :)

**Comment by larobert** [comment]
Maybe I am not understanding a hard set, but each line was input with a the corresponding male or female voice. Otherwise please explain more in detail. Not a tech guy here. :)

Robert Corvin
(323) 360-3500
www.robercorvin.com
www.IMDB.me/robertcorvin

**Comment by mattvv** [comment]
Not a problem Robert!

There's a bug in the app at the moment where lines that don't have a gender set crash the app on line playing.
If you let me know your Script Name I can go in and hard set this until the fix is in, otherwise you could hard set yourself by going to edit line and changing the gender to male.

As soon as the version 1.1.4 comes out however this should be resolved! I am working hard to fix it!

**Comment by larobert** [comment]
Hi Matt, the script is Guy Gal.  Thanks!

Robert

On Wed, Mar 28, 2012 at 2:10 PM, Matt Van <
reply@reply.github.com

**Comment by mattvv** [comment]
Hey Robert, I hard set the lines that didn't have a gender to Female, Please try now.

**Comment by larobert** [comment]
Thanks Matt!

**Comment by mattvv** [comment]
Not a problem, While you're at it - I'd love it if you could give us a great review on the App Store. This Software is Free to use and I make absolutely no money from it - The only thing that keeps the project going at the moment is the satisfaction of helping actors like you! Please support me by rating the app higher so others searching for the App store can find and use the app for free too!

Matt
